org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8

modbench_version=0.1.1
minecraft_version=26.1.2
neo_version=26.1.2.76
mod_version=1.0.0
mod_id=simplebench
mod_name=Simple Bench Target
mod_group_id=com.zhongbai233.example
