org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
modBenchVersion=0.1.0-SNAPSHOT
modBenchApiVersion=0.1.0-SNAPSHOT
modBenchRuntimeVersion=0.1.0-SNAPSHOT
modBenchGradlePluginVersion=0.1.0-SNAPSHOT
minecraftVersion=26.1.2
neoForgeVersion=26.1.2.76
modDevVersion=2.0.141